# Perform the following analysis on the provided file "demo.csv".


## 1. Which month saw the highest joining of the employees

   function name: max_joinings_month()
   
   inputs: DataFrame
   
   outputs: str
   
   
## 2. What is the mean salary is the state KS
   
   function name: mean_ks_salary()
   
   inputs: DataFrame
   
   outputs: float
   
   
## 3. Which Region has highest mean salary
   
   function name: max_mean_salary_region()
   
   inputs: DataFrame
   
   outputs: str
   
   
## 4. Which region has lowest mean salary
   
   function name: min_mean_salary_region()
   
   inputs: DataFrame
   
   outputs: str
   
   
## 5. Which City has highest mean weight
   
   function name: max_mean_weight_city()
   
   inputs: DataFrame
   
   outputs: str
   
   
## 6. What is the difference between mean salary of Doctors and Professors
   
   function name: dr_prof_mean_salary_diff()
   
   inputs: DataFrame
   
   outputs: float
   
   
## 7. How many female use yahoo
   
   function name: females_with_yahoo()
   
   inputs: DataFrame
   
   outputs: int
   
   
## 8. How many Doctors use gmail
   
   function name: doctors_with_gmail()
   
   inputs: DataFrame
   
   outputs: int
   
   
## 9. What is the password of the youngest male
   
   function name: youngest_male_password()
   
   inputs: DataFrame
   
   outputs: str

In [1]:
import pandas as pd
df = pd.read_csv('demo.csv')
df

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,850297,Ms.,Shawna,W,Buck,F,shawna.buck@gmail.com,Rosario Buck,Keisha Buck,Hendricks,...,222-11-7603,702-771-7149,Las Vegas,Clark,Las Vegas,NV,89128,West,swbuck,ja8?k3BTF^]o@<&
1,304721,Mr.,Nathaniel,Z,Burke,M,nathaniel.burke@walmart.com,Derrick Burke,Phoebe Burke,Pugh,...,550-99-9897,231-765-6923,Irons,Lake,Irons,MI,49644,Midwest,nzburke,YoungestMale#2026
2,412317,Drs.,Elisabeth,W,Foster,F,elisabeth.foster@gmail.com,Irwin Foster,Janie Foster,Delaney,...,215-91-0004,270-749-4774,Lexington,Fayette,Lexington,KY,40501,South,ewfoster,5D.B4IGNkWJfG<~
3,621375,Mrs.,Briana,C,Lancaster,F,briana.lancaster@yahoo.com,Jeffrey Lancaster,Shelby Lancaster,Weiss,...,534-71-1053,219-623-8216,Munster,Lake,Munster,IN,46321,Midwest,bclancaster,I%?JDM;pW
4,787549,Hon.,Estella,L,Potter,F,estella.potter@gmail.com,Booker Potter,Katelyn Potter,Pate,...,644-29-6396,907-677-8486,Fairbanks,Fairbanks North Star,Fairbanks,AK,99709,West,elpotter,j4jkEXfC&Rh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,900201,Mr.,Daniel,T,Jackson,M,daniel.jackson201@outlook.com,Father Jackson,Mother Jackson,Maiden201,...,352-27-5188,289-356-3890,Detroit,Wayne,Detroit,MI,48201,Midwest,djackson201,Pw201!xA9#
201,900202,Mrs.,Shawna,U,Brown,F,shawna.brown202@yahoo.com,Father Brown,Mother Brown,Maiden202,...,645-90-3694,566-223-9988,Philadelphia,Philadelphia,Philadelphia,PA,19103,Northeast,sbrown202,Pw202!xA9#
202,900203,Mr.,Daniel,V,Jackson,M,daniel.jackson203@yahoo.com,Father Jackson,Mother Jackson,Maiden203,...,201-66-8649,307-884-4368,San Diego,San Diego,San Diego,CA,92101,West,djackson203,Pw203!xA9#
203,900204,Mr.,Estella,W,Brown,F,estella.brown204@outlook.com,Father Brown,Mother Brown,Maiden204,...,813-41-3511,404-415-6916,San Diego,San Diego,San Diego,CA,92101,West,ebrown204,Pw204!xA9#
204,900205,Mrs.,Nathaniel,X,Johnson,M,nathaniel.johnson205@outlook.com,Father Johnson,Mother Johnson,Maiden205,...,670-75-2607,675-686-5386,Kansas City,Wyandotte,Kansas City,KS,66101,Midwest,njohnson205,Pw205!xA9#

In [2]:
df.columns

Index(['Emp ID', 'Name Prefix', 'First Name', 'Middle Initial', 'Last Name',
       'Gender', 'E Mail', 'Father's Name', 'Mother's Name',
       'Mother's Maiden Name', 'Date of Birth', 'Time of Birth', 'Age in Yrs.',
       'Weight in Kgs.', 'Date of Joining', 'Quarter of Joining',
       'Half of Joining', 'Year of Joining', 'Month of Joining',
       'Month Name of Joining', 'Short Month', 'Day of Joining',
       'DOW of Joining', 'Short DOW', 'Age in Company (Years)', 'Salary',
       'Last % Hike', 'SSN', 'Phone No. ', 'Place Name', 'County', 'City',
       'State', 'Zip', 'Region', 'User Name', 'Password'],
      dtype='str')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Emp ID                  205 non-null    int64
 1   Name Prefix             205 non-null    str
 2   First Name              205 non-null    str
 3   Middle Initial          205 non-null    str
 4   Last Name               205 non-null    str
 5   Gender                  205 non-null    str
 6   E Mail                  205 non-null    str
 7   Father's Name           205 non-null    str
 8   Mother's Name           205 non-null    str
 9   Mother's Maiden Name    205 non-null    str
 10  Date of Birth           205 non-null    str
 11  Time of Birth           205 non-null    str
 12  Age in Yrs.             205 non-null    float64
 13  Weight in Kgs.          205 non-null    int64
 14  Date of Joining         205 non-null    str
 15  Quarter of Joining      205 non-null    str
 16  Half of Joining         205 non-null    str
 17  Year of Joining         205 non-null    int64
 18  Month of Joining        205 non-null    int64
 19  Month Name of Joining   205 non-null    str
 20  Short Month             205 non-null    str
 21  Day of Joining          205 non-null    int64
 22  DOW of Joining          205 non-null    str
 23  Short DOW               205 non-null    str
 24  Age in Company (Years)  205 non-null    float64
 25  Salary                  205 non-null    int64
 26  Last % Hike             205 non-null    str
 27  SSN                     205 non-null    str
 28  Phone No.               205 non-null    str
 29  Place Name              205 non-null    str
 30  County                  205 non-null    str
 31  City                    205 non-null    str
 32  State                   205 non-null    str
 33  Zip                     205 non-null    int64
 34  Region                  205 non-null    str
 35  User Name               205 non-null    str
 36  Password                205 non-null    str
dtypes: float64(2), int64(7), str(28)
memory usage: 59.4 KB

In [4]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,195,196,197,198,199,200,201,202,203,204
Emp ID,850297,304721,412317,621375,787549,900006,900007,900008,900009,900010,...,900196,900197,900198,900199,900200,900201,900202,900203,900204,900205
Name Prefix,Ms.,Mr.,Drs.,Mrs.,Hon.,Mr.,Dr.,Dr.,Ms.,Ms.,...,Ms.,Ms.,Prof.,Dr.,Mr.,Mr.,Mrs.,Mr.,Mr.,Mrs.
First Name,Shawna,Nathaniel,Elisabeth,Briana,Estella,Shawna,Nathaniel,Sarah,Charles,Shawna,...,Estella,Daniel,Jennifer,Charles,Sarah,Daniel,Shawna,Daniel,Estella,Nathaniel
Middle Initial,W,Z,W,C,L,G,H,I,J,K,...,O,P,Q,R,S,T,U,V,W,X
Last Name,Buck,Burke,Foster,Lancaster,Potter,Miller,Moore,Taylor,Jackson,Davis,...,Anderson,Taylor,Jackson,Moore,Davis,Jackson,Brown,Jackson,Brown,Johnson
Gender,F,M,F,F,F,F,M,F,M,F,...,F,M,F,M,F,M,F,M,F,M
E Mail,shawna.buck@gmail.com,nathaniel.burke@walmart.com,elisabeth.foster@gmail.com,briana.lancaster@yahoo.com,estella.potter@gmail.com,shawna.miller6@walmart.com,nathaniel.moore7@gmail.com,sarah.taylor8@gmail.com,charles.jackson9@walmart.com,shawna.davis10@gmail.com,...,estella.anderson196@yahoo.com,daniel.taylor197@yahoo.com,jennifer.jackson198@gmail.com,charles.moore199@yahoo.com,sarah.davis200@walmart.com,daniel.jackson201@outlook.com,shawna.brown202@yahoo.com,daniel.jackson203@yahoo.com,estella.brown204@outlook.com,nathaniel.johnson205@outlook.com
Father's Name,Rosario Buck,Derrick Burke,Irwin Foster,Jeffrey Lancaster,Booker Potter,Father Miller,Father Moore,Father Taylor,Father Jackson,Father Davis,...,Father Anderson,Father Taylor,Father Jackson,Father Moore,Father Davis,Father Jackson,Father Brown,Father Jackson,Father Brown,Father Johnson
Mother's Name,Keisha Buck,Phoebe Burke,Janie Foster,Shelby Lancaster,Katelyn Potter,Mother Miller,Mother Moore,Mother Taylor,Mother Jackson,Mother Davis,...,Mother Anderson,Mother Taylor,Mother Jackson,Mother Moore,Mother Davis,Mother Jackson,Mother Brown,Mother Jackson,Mother Brown,Mother Johnson
Mother's Maiden Name,Hendricks,Pugh,Delaney,Weiss,Pate,Maiden6,Maiden7,Maiden8,Maiden9,Maiden10,...,Maiden196,Maiden197,Maiden198,Maiden199,Maiden200,Maiden201,Maiden202,Maiden203,Maiden204,Maiden205
Date of Birth,12/12/1971,10/31/1993,11/26/1994,11/24/1975,3/13/1995,02/23/1990,09/13/1971,03/25/1972,03/17/1985,08/08/1973,...,08/05/1960,02/16/1968,04/10/1969,12/26/1984,10/30/1957,05/19/1975,10/10/1981,06/20/1962,03/20/1964,12/26/1987
Time of Birth,06:34:47 AM,02:02:38 AM,03:48:27 PM,09:44:16 PM,09:30:28 PM,06:54:03 AM,01:05:42 AM,01:25:57 AM,03:21:21 AM,11:18:31 AM,...,03:48:10 AM,06:28:40 AM,04:36:53 AM,05:04:46 AM,09:36:16 AM,12:59:18 AM,12:23:58 AM,07:52:23 AM,07:51:59 AM,09:13:35 AM
Age in Yrs.,45.66,18.01,22.68,41.7,22.39,36.48,54.93,54.4,41.42,53.02,...,66.03,58.5,57.35,41.64,68.8,51.25,44.85,64.16,62.41,38.64
Weight in Kgs.,44,52,42,43,58,79,73,83,76,79,...,53,60,72,46,54,82,78,73,69,74
Date of Joining,12/18/2010,4/25/2017,3/27/2017,2/25/2003,10/11/2016,11/4/2013,11/1/2007,11/17/2015,11/24/2010,11/12/2005,...,7/18/2005,1/18/2014,1/13/2014,4/6/2014,7/3/2012,2/22/2008,2/25/2008,3/4/2011,4/13/2018,1/12/2018
Quarter of Joining,Q4,Q2,Q1,Q1,Q4,Q4,Q4,Q4,Q4,Q4,...,Q3,Q1,Q1,Q2,Q3,Q1,Q1,Q1,Q2,Q1
Half of Joining,H2,H1,H1,H1,H2,H2,H2,H2,H2,H2,...,H2,H1,H1,H1,H2,H1,H1,H1,H1,H1
Year of Joining,2010,2017,2017,2003,2016,2013,2007,2015,2010,2005,...,2005,2014,2014,2014,2012,2008,2008,2011,2018,2018
Month of Joining,12,4,3,2,10,11,11,11,11,11,...,7,1,1,4,7,2,2,3,4,1
Month Name of Joining,December,April,March,February,October,November,November,November,November,November,...,July,January,January,April,July,February,February,March,April,January
Short Month,Dec,Apr,Mar,Feb,Oct,Nov,Nov,Nov,Nov,Nov,...,Jul,Jan,Jan,Apr,Jul,Feb,Feb,Mar,Apr,Jan
Day of Joining,18,25,27,25,11,4,1,17,24,12,...,18,18,13,6,3,22,25,4,13,12
DOW of Joining,Saturday,Tuesday,Monday,Tuesday,Tuesday,Monday,Thursday,Tuesday,Wednesday,Saturday,...,Monday,Saturday,Monday,Sunday,Tuesday,Friday,Monday,Friday,Friday,Friday
Short DOW,Sat,Tue,Mon,Tue,Tue,Mon,Thu,Tue,Wed,Sat,...,Mon,Sat,Mon,Sun,Tue,Fri,Mon,Fri,Fri,Fri
Age in Company (Years),6.61,0.26,0.34,14.43,0.79,12.78,18.79,10.75,15.73,20.76,...,21.08,12.58,12.59,12.36,14.12,18.48,18.48,15.46,8.34,8.59
Salary,119090,117991,161045,142616,135706,111211,161993,168389,94969,126647,...,118840,83912,111201,149062,117913,90663,133337,108627,108986,83750
Last % Hike,17%,14%,28%,16%,11%,10%,9%,29%,22%,29%,...,24%,17%,15%,11%,23%,23%,10%,24%,18%,21%
SSN,222-11-7603,550-99-9897,215-91-0004,534-71-1053,644-29-6396,238-53-6468,229-12-5780,761-75-8116,500-19-8483,745-39-9915,...,498-69-8816,360-79-5696,993-17-7265,233-13-7591,757-20-1145,352-27-5188,645-90-3694,201-66-8649,813-41-3511,670-75-2607
Phone No.,702-771-7149,231-765-6923,270-749-4774,219-623-8216,907-677-8486,918-451-3683,640-787-8813,901-751-8964,596-786-6506,695-381-3519,...,658-927-9053,869-670-1211,782-959-6425,480-832-3051,813-627-5398,289-356-3890,566-223-9988,307-884-4368,404-415-6916,675-686-5386
Place Name,Las Vegas,Irons,Lexington,Munster,Fairbanks,San Diego,Los Angeles,New York,Topeka,Philadelphia,...,San Diego,Chicago,Kansas City,Atlanta,Los Angeles,Detroit,Philadelphia,San Diego,San Diego,Kansas City
County,Clark,Lake,Fayette,Lake,Fairbanks North Star,San Diego,Los Angeles,New York,Shawnee,Philadelphia,...,San Diego,Cook,Wyandotte,Fulton,Los Angeles,Wayne,Philadelphia,San Diego,San Diego,Wyandotte
City,Las Vegas,Irons,Lexington,Munster,Fairbanks,San Diego,Los Angeles,New York,Topeka,Philadelphia,...,San Diego,Chicago,Kansas City,Atlanta,Los Angeles,Detroit,Philadelphia,San Diego,San Diego,Kansas City
State,NV,MI,KY,IN,AK,CA,CA,NY,KS,PA,...,CA,IL,KS,GA,CA,MI,PA,CA,CA,KS
Zip,89128,49644,40501,46321,99709,92101,90001,10001,66603,19103,...,92101,60601,66101,30303,90001,48201,19103,92101,92101,66101
Region,West,Midwest,South,Midwest,West,West,West,Northeast,Midwest,Northeast,...,West,Midwest,Midwest,South,West,Midwest,Northeast,West,West,Midwest
User Name,swbuck,nzburke,ewfoster,bclancaster,elpotter,smiller6,nmoore7,staylor8,cjackson9,sdavis10,...,eanderson196,dtaylor197,jjackson198,cmoore199,sdavis200,djackson201,sbrown202,djackson203,ebrown204,njohnson205
Password,ja8?k3BTF^]o@<&,YoungestMale#2026,5D.B4IGNkWJfG<~,I%?JDM;pW,j4jkEXfC&Rh,Pw6!xA9#,Pw7!xA9#,Pw8!xA9#,Pw9!xA9#,Pw10!xA9#,...,Pw196!xA9#,Pw197!xA9#,Pw198!xA9#,Pw199!xA9#,Pw200!xA9#,Pw201!xA9#,Pw202!xA9#,Pw203!xA9#,Pw204!xA9#,Pw205!xA9#

## 1. Which month saw the highest joining of the employees

   function name: max_joinings_month()
   
   inputs: DataFrame
   
   outputs: str

In [ ]:
df[["Month Name of Joining","Month of Joining"]].head()

  Month Name of Joining  Month of Joining
0              December                12
1                 April                 4
2                 March                 3
3              February                 2
4               October                10

In [20]:
def max_joining_month(df):
    highest_joining = df['Month Name of Joining'].value_counts()
    month =  highest_joining.idxmax()
    joining = highest_joining.max()
    return f"{month}, has the highest number of joining which is  {joining}"
max_joining_month(df)

'November, has the highest number of joining which is  80'

## 2. What is the mean salary is the state KS
   
   function name: mean_ks_salary()
   
   inputs: DataFrame
   
   outputs: float

In [26]:
def mean_ks_salary(df):
    mean_salary = df[df['State']=='KS']['Salary'].mean()
    return mean_salary
mean_ks_salary(df)

np.float64(97919.15384615384)

## 3. Which Region has highest mean salary
   
   function name: max_mean_salary_region()
   
   inputs: DataFrame
   
   outputs: str

In [31]:
def max_mean_salary_region(df):
    max_region = df.groupby('Region')['Salary'].mean()
    region = max_region.idxmax()
    salary = max_region.max()
    return f"{region} have the highest mean salary {salary}"
max_mean_salary_region(df)

'Northeast have the highest mean salary 139898.20454545456'

## 4. Which region has lowest mean salary
   
   function name: min_mean_salary_region()
   
   inputs: DataFrame
   
   outputs: str

In [33]:
def min_mean_salary_region(df):
    min_region = df.groupby('Region')['Salary'].mean()
    region = min_region.idxmin()
    salary = min_region.min()
    return f"{region} have the lowest mean salary {salary}"
min_mean_salary_region(df)

'Midwest have the lowest mean salary 99701.55882352941'

## 5. Which City has highest mean weight
   
   function name: max_mean_weight_city()
   
   inputs: DataFrame
   
   outputs: str

In [41]:
def max_mean_weight_city(df):
    max_weight = df.groupby('City')['Weight in Kgs.'].agg('mean')
    return max_weight.idxmax(), max_weight.max()
max_mean_weight_city(df)

('Wichita', np.float64(100.0))

## 6. What is the difference between mean salary of Doctors and Professors
   
   function name: dr_prof_mean_salary_diff()
   
   inputs: DataFrame
   
   outputs: float

In [44]:
df[['Name Prefix']].to_string()

'    Name Prefix\n0           Ms.\n1           Mr.\n2          Drs.\n3          Mrs.\n4          Hon.\n5           Mr.\n6           Dr.\n7           Dr.\n8           Ms.\n9           Ms.\n10          Ms.\n11         Mrs.\n12          Mr.\n13         Hon.\n14          Dr.\n15        Prof.\n16          Mr.\n17         Mrs.\n18          Ms.\n19          Dr.\n20          Dr.\n21          Dr.\n22          Dr.\n23          Dr.\n24          Dr.\n25          Dr.\n26          Dr.\n27          Dr.\n28          Dr.\n29          Dr.\n30          Dr.\n31          Dr.\n32          Dr.\n33          Dr.\n34        Prof.\n35        Prof.\n36        Prof.\n37        Prof.\n38        Prof.\n39        Prof.\n40        Prof.\n41        Prof.\n42        Prof.\n43        Prof.\n44          Mr.\n45         Mrs.\n46          Mr.\n47          Mr.\n48          Mr.\n49          Ms.\n50          Dr.\n51          Mr.\n52          Ms.\n53          Ms.\n54          Ms.\n55         Mrs.\n56          Ms.\n57          Mr.\n58          Dr.\n59         Hon.\n60         Mrs.\n61          Mr.\n62          Dr.\n63          Mr.\n64         Mrs.\n65          Ms.\n66          Ms.\n67          Mr.\n68          Mr.\n69         Mrs.\n70          Mr.\n71          Dr.\n72          Mr.\n73          Ms.\n74          Dr.\n75          Ms.\n76         Hon.\n77          Mr.\n78         Mrs.\n79          Mr.\n80          Mr.\n81          Dr.\n82          Mr.\n83          Ms.\n84          Ms.\n85        Prof.\n86          Mr.\n87          Dr.\n88          Dr.\n89         Mrs.\n90          Ms.\n91          Mr.\n92          Dr.\n93          Ms.\n94          Dr.\n95        Prof.\n96         Mrs.\n97         Mrs.\n98        Prof.\n99        Prof.\n100        Mrs.\n101         Ms.\n102         Dr.\n103        Mrs.\n104       Prof.\n105         Mr.\n106         Ms.\n107         Ms.\n108       Prof.\n109       Prof.\n110         Ms.\n111         Mr.\n112        Mrs.\n113         Mr.\n114         Mr.\n115         Mr.\n116         Dr.\n117         Ms.\n118         Ms.\n119         Ms.\n120        Hon.\n121         Ms.\n122         Ms.\n123        Hon.\n124         Ms.\n125         Mr.\n126         Mr.\n127         Mr.\n128         Mr.\n129         Mr.\n130         Ms.\n131         Mr.\n132         Dr.\n133        Mrs.\n134         Dr.\n135         Mr.\n136        Hon.\n137        Mrs.\n138         Mr.\n139         Ms.\n140         Mr.\n141         Ms.\n142        Hon.\n143         Mr.\n144         Ms.\n145         Mr.\n146        Mrs.\n147         Mr.\n148         Mr.\n149         Ms.\n150        Mrs.\n151         Dr.\n152         Ms.\n153         Ms.\n154         Ms.\n155         Mr.\n156         Ms.\n157        Mrs.\n158         Ms.\n159         Mr.\n160         Mr.\n161         Mr.\n162         Mr.\n163        Mrs.\n164         Ms.\n165       Prof.\n166         Ms.\n167         Ms.\n168        Mrs.\n169         Ms.\n170         Ms.\n171         Dr.\n172         Ms.\n173         Ms.\n174        Mrs.\n175         Mr.\n176         Mr.\n177         Mr.\n178         Mr.\n179         Mr.\n180         Ms.\n181         Ms.\n182         Dr.\n183        Mrs.\n184        Hon.\n185         Mr.\n186         Ms.\n187         Ms.\n188         Ms.\n189         Mr.\n190         Mr.\n191         Dr.\n192         Dr.\n193         Ms.\n194       Prof.\n195         Ms.\n196         Ms.\n197       Prof.\n198         Dr.\n199         Mr.\n200         Mr.\n201        Mrs.\n202         Mr.\n203         Mr.\n204        Mrs.'

In [49]:
def dr_prof_mean_salary_diff(df):
    dr_mean_salary = df[df['Name Prefix']=='Drs.']['Salary'].mean()
    prof_mean_salary = df[df['Name Prefix']=='Prof.']['Salary'].mean()
    diff = dr_mean_salary-prof_mean_salary
    return diff
dr_prof_mean_salary_diff(df)

np.float64(37576.19047619047)

## 7. How many female use yahoo
   
   function name: females_with_yahoo()
   
   inputs: DataFrame
   
   outputs: int

In [68]:
def females_with_yahoo(df):
    yahoo = df[(df['Gender']=='F') &(df['E Mail'].str.split('@').str[-1]=='yahoo.com')]
    return len(yahoo)
females_with_yahoo(df)

37

In [63]:
def females_with_yahoo(df):
    yahoo = df[(df['Gender']=='F') &(df['E Mail'].str.endswith('@yahoo.com', na = False))]
    return len(yahoo)
females_with_yahoo(df)

37

## 8. How many Doctors use gmail
   
   function name: doctors_with_gmail()
   
   inputs: DataFrame
   
   outputs: int

In [73]:
def doctors_with_gmail(df):
    gmail = df[(df['Name Prefix']=='Drs.') & (df['E Mail'].str.endswith('@gmail.com', na = False))]
    return len(gmail)
doctors_with_gmail(df)

1

## 9. What is the password of the youngest male
   
   function name: youngest_male_password()
   
   inputs: DataFrame
   
   outputs: str

In [84]:
def youngest_male_password(df):
    male = df[df['Gender'] == 'M']
    password = male.loc[male['Age in Yrs.'].idxmin(), ['Password']]
    return password
youngest_male_password(df)

Password    YoungestMale#2026
Name: 1, dtype: str